/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/boss3/jorg

// This file generated by ModelGen - Do NOT Modify

#define BOSS31_FRAME_attak101        	0
#define BOSS31_FRAME_attak102        	1
#define BOSS31_FRAME_attak103        	2
#define BOSS31_FRAME_attak104        	3
#define BOSS31_FRAME_attak105        	4
#define BOSS31_FRAME_attak106        	5
#define BOSS31_FRAME_attak107        	6
#define BOSS31_FRAME_attak108        	7
#define BOSS31_FRAME_attak109        	8
#define BOSS31_FRAME_attak110        	9
#define BOSS31_FRAME_attak111        	10
#define BOSS31_FRAME_attak112        	11
#define BOSS31_FRAME_attak113        	12
#define BOSS31_FRAME_attak114        	13
#define BOSS31_FRAME_attak115        	14
#define BOSS31_FRAME_attak116        	15
#define BOSS31_FRAME_attak117        	16
#define BOSS31_FRAME_attak118        	17
#define BOSS31_FRAME_attak201        	18
#define BOSS31_FRAME_attak202        	19
#define BOSS31_FRAME_attak203        	20
#define BOSS31_FRAME_attak204        	21
#define BOSS31_FRAME_attak205        	22
#define BOSS31_FRAME_attak206        	23
#define BOSS31_FRAME_attak207        	24
#define BOSS31_FRAME_attak208        	25
#define BOSS31_FRAME_attak209        	26
#define BOSS31_FRAME_attak210        	27
#define BOSS31_FRAME_attak211        	28
#define BOSS31_FRAME_attak212        	29
#define BOSS31_FRAME_attak213        	30
#define BOSS31_FRAME_death01         	31
#define BOSS31_FRAME_death02         	32
#define BOSS31_FRAME_death03         	33
#define BOSS31_FRAME_death04         	34
#define BOSS31_FRAME_death05         	35
#define BOSS31_FRAME_death06         	36
#define BOSS31_FRAME_death07         	37
#define BOSS31_FRAME_death08         	38
#define BOSS31_FRAME_death09         	39
#define BOSS31_FRAME_death10         	40
#define BOSS31_FRAME_death11         	41
#define BOSS31_FRAME_death12         	42
#define BOSS31_FRAME_death13         	43
#define BOSS31_FRAME_death14         	44
#define BOSS31_FRAME_death15         	45
#define BOSS31_FRAME_death16         	46
#define BOSS31_FRAME_death17         	47
#define BOSS31_FRAME_death18         	48
#define BOSS31_FRAME_death19         	49
#define BOSS31_FRAME_death20         	50
#define BOSS31_FRAME_death21         	51
#define BOSS31_FRAME_death22         	52
#define BOSS31_FRAME_death23         	53
#define BOSS31_FRAME_death24         	54
#define BOSS31_FRAME_death25         	55
#define BOSS31_FRAME_death26         	56
#define BOSS31_FRAME_death27         	57
#define BOSS31_FRAME_death28         	58
#define BOSS31_FRAME_death29         	59
#define BOSS31_FRAME_death30         	60
#define BOSS31_FRAME_death31         	61
#define BOSS31_FRAME_death32         	62
#define BOSS31_FRAME_death33         	63
#define BOSS31_FRAME_death34         	64
#define BOSS31_FRAME_death35         	65
#define BOSS31_FRAME_death36         	66
#define BOSS31_FRAME_death37         	67
#define BOSS31_FRAME_death38         	68
#define BOSS31_FRAME_death39         	69
#define BOSS31_FRAME_death40         	70
#define BOSS31_FRAME_death41         	71
#define BOSS31_FRAME_death42         	72
#define BOSS31_FRAME_death43         	73
#define BOSS31_FRAME_death44         	74
#define BOSS31_FRAME_death45         	75
#define BOSS31_FRAME_death46         	76
#define BOSS31_FRAME_death47         	77
#define BOSS31_FRAME_death48         	78
#define BOSS31_FRAME_death49         	79
#define BOSS31_FRAME_death50         	80
#define BOSS31_FRAME_pain101         	81
#define BOSS31_FRAME_pain102         	82
#define BOSS31_FRAME_pain103         	83
#define BOSS31_FRAME_pain201         	84
#define BOSS31_FRAME_pain202         	85
#define BOSS31_FRAME_pain203         	86
#define BOSS31_FRAME_pain301         	87
#define BOSS31_FRAME_pain302         	88
#define BOSS31_FRAME_pain303         	89
#define BOSS31_FRAME_pain304         	90
#define BOSS31_FRAME_pain305         	91
#define BOSS31_FRAME_pain306         	92
#define BOSS31_FRAME_pain307         	93
#define BOSS31_FRAME_pain308         	94
#define BOSS31_FRAME_pain309         	95
#define BOSS31_FRAME_pain310         	96
#define BOSS31_FRAME_pain311         	97
#define BOSS31_FRAME_pain312         	98
#define BOSS31_FRAME_pain313         	99
#define BOSS31_FRAME_pain314         	100
#define BOSS31_FRAME_pain315         	101
#define BOSS31_FRAME_pain316         	102
#define BOSS31_FRAME_pain317         	103
#define BOSS31_FRAME_pain318         	104
#define BOSS31_FRAME_pain319         	105
#define BOSS31_FRAME_pain320         	106
#define BOSS31_FRAME_pain321         	107
#define BOSS31_FRAME_pain322         	108
#define BOSS31_FRAME_pain323         	109
#define BOSS31_FRAME_pain324         	110
#define BOSS31_FRAME_pain325         	111
#define BOSS31_FRAME_stand01         	112
#define BOSS31_FRAME_stand02         	113
#define BOSS31_FRAME_stand03         	114
#define BOSS31_FRAME_stand04         	115
#define BOSS31_FRAME_stand05         	116
#define BOSS31_FRAME_stand06         	117
#define BOSS31_FRAME_stand07         	118
#define BOSS31_FRAME_stand08         	119
#define BOSS31_FRAME_stand09         	120
#define BOSS31_FRAME_stand10         	121
#define BOSS31_FRAME_stand11         	122
#define BOSS31_FRAME_stand12         	123
#define BOSS31_FRAME_stand13         	124
#define BOSS31_FRAME_stand14         	125
#define BOSS31_FRAME_stand15         	126
#define BOSS31_FRAME_stand16         	127
#define BOSS31_FRAME_stand17         	128
#define BOSS31_FRAME_stand18         	129
#define BOSS31_FRAME_stand19         	130
#define BOSS31_FRAME_stand20         	131
#define BOSS31_FRAME_stand21         	132
#define BOSS31_FRAME_stand22         	133
#define BOSS31_FRAME_stand23         	134
#define BOSS31_FRAME_stand24         	135
#define BOSS31_FRAME_stand25         	136
#define BOSS31_FRAME_stand26         	137
#define BOSS31_FRAME_stand27         	138
#define BOSS31_FRAME_stand28         	139
#define BOSS31_FRAME_stand29         	140
#define BOSS31_FRAME_stand30         	141
#define BOSS31_FRAME_stand31         	142
#define BOSS31_FRAME_stand32         	143
#define BOSS31_FRAME_stand33         	144
#define BOSS31_FRAME_stand34         	145
#define BOSS31_FRAME_stand35         	146
#define BOSS31_FRAME_stand36         	147
#define BOSS31_FRAME_stand37         	148
#define BOSS31_FRAME_stand38         	149
#define BOSS31_FRAME_stand39         	150
#define BOSS31_FRAME_stand40         	151
#define BOSS31_FRAME_stand41         	152
#define BOSS31_FRAME_stand42         	153
#define BOSS31_FRAME_stand43         	154
#define BOSS31_FRAME_stand44         	155
#define BOSS31_FRAME_stand45         	156
#define BOSS31_FRAME_stand46         	157
#define BOSS31_FRAME_stand47         	158
#define BOSS31_FRAME_stand48         	159
#define BOSS31_FRAME_stand49         	160
#define BOSS31_FRAME_stand50         	161
#define BOSS31_FRAME_stand51         	162
#define BOSS31_FRAME_walk01          	163
#define BOSS31_FRAME_walk02          	164
#define BOSS31_FRAME_walk03          	165
#define BOSS31_FRAME_walk04          	166
#define BOSS31_FRAME_walk05          	167
#define BOSS31_FRAME_walk06          	168
#define BOSS31_FRAME_walk07          	169
#define BOSS31_FRAME_walk08          	170
#define BOSS31_FRAME_walk09          	171
#define BOSS31_FRAME_walk10          	172
#define BOSS31_FRAME_walk11          	173
#define BOSS31_FRAME_walk12          	174
#define BOSS31_FRAME_walk13          	175
#define BOSS31_FRAME_walk14          	176
#define BOSS31_FRAME_walk15          	177
#define BOSS31_FRAME_walk16          	178
#define BOSS31_FRAME_walk17          	179
#define BOSS31_FRAME_walk18          	180
#define BOSS31_FRAME_walk19          	181
#define BOSS31_FRAME_walk20          	182
#define BOSS31_FRAME_walk21          	183
#define BOSS31_FRAME_walk22          	184
#define BOSS31_FRAME_walk23          	185
#define BOSS31_FRAME_walk24          	186
#define BOSS31_FRAME_walk25          	187

#define BOSS31_MODEL_SCALE		1.000000
