/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/boss2

// This file generated by ModelGen - Do NOT Modify

#define BOSS2_FRAME_stand30         	0
#define BOSS2_FRAME_stand31         	1
#define BOSS2_FRAME_stand32         	2
#define BOSS2_FRAME_stand33         	3
#define BOSS2_FRAME_stand34         	4
#define BOSS2_FRAME_stand35         	5
#define BOSS2_FRAME_stand36         	6
#define BOSS2_FRAME_stand37         	7
#define BOSS2_FRAME_stand38         	8
#define BOSS2_FRAME_stand39         	9
#define BOSS2_FRAME_stand40         	10
#define BOSS2_FRAME_stand41         	11
#define BOSS2_FRAME_stand42         	12
#define BOSS2_FRAME_stand43         	13
#define BOSS2_FRAME_stand44         	14
#define BOSS2_FRAME_stand45         	15
#define BOSS2_FRAME_stand46         	16
#define BOSS2_FRAME_stand47         	17
#define BOSS2_FRAME_stand48         	18
#define BOSS2_FRAME_stand49         	19
#define BOSS2_FRAME_stand50         	20
#define BOSS2_FRAME_stand1          	21
#define BOSS2_FRAME_stand2          	22
#define BOSS2_FRAME_stand3          	23
#define BOSS2_FRAME_stand4          	24
#define BOSS2_FRAME_stand5          	25
#define BOSS2_FRAME_stand6          	26
#define BOSS2_FRAME_stand7          	27
#define BOSS2_FRAME_stand8          	28
#define BOSS2_FRAME_stand9          	29
#define BOSS2_FRAME_stand10         	30
#define BOSS2_FRAME_stand11         	31
#define BOSS2_FRAME_stand12         	32
#define BOSS2_FRAME_stand13         	33
#define BOSS2_FRAME_stand14         	34
#define BOSS2_FRAME_stand15         	35
#define BOSS2_FRAME_stand16         	36
#define BOSS2_FRAME_stand17         	37
#define BOSS2_FRAME_stand18         	38
#define BOSS2_FRAME_stand19         	39
#define BOSS2_FRAME_stand20         	40
#define BOSS2_FRAME_stand21         	41
#define BOSS2_FRAME_stand22         	42
#define BOSS2_FRAME_stand23         	43
#define BOSS2_FRAME_stand24         	44
#define BOSS2_FRAME_stand25         	45
#define BOSS2_FRAME_stand26         	46
#define BOSS2_FRAME_stand27         	47
#define BOSS2_FRAME_stand28         	48
#define BOSS2_FRAME_stand29         	49
#define BOSS2_FRAME_walk1           	50
#define BOSS2_FRAME_walk2           	51
#define BOSS2_FRAME_walk3           	52
#define BOSS2_FRAME_walk4           	53
#define BOSS2_FRAME_walk5           	54
#define BOSS2_FRAME_walk6           	55
#define BOSS2_FRAME_walk7           	56
#define BOSS2_FRAME_walk8           	57
#define BOSS2_FRAME_walk9           	58
#define BOSS2_FRAME_walk10          	59
#define BOSS2_FRAME_walk11          	60
#define BOSS2_FRAME_walk12          	61
#define BOSS2_FRAME_walk13          	62
#define BOSS2_FRAME_walk14          	63
#define BOSS2_FRAME_walk15          	64
#define BOSS2_FRAME_walk16          	65
#define BOSS2_FRAME_walk17          	66
#define BOSS2_FRAME_walk18          	67
#define BOSS2_FRAME_walk19          	68
#define BOSS2_FRAME_walk20          	69
#define BOSS2_FRAME_attack1         	70
#define BOSS2_FRAME_attack2         	71
#define BOSS2_FRAME_attack3         	72
#define BOSS2_FRAME_attack4         	73
#define BOSS2_FRAME_attack5         	74
#define BOSS2_FRAME_attack6         	75
#define BOSS2_FRAME_attack7         	76
#define BOSS2_FRAME_attack8         	77
#define BOSS2_FRAME_attack9         	78
#define BOSS2_FRAME_attack10        	79
#define BOSS2_FRAME_attack11        	80
#define BOSS2_FRAME_attack12        	81
#define BOSS2_FRAME_attack13        	82
#define BOSS2_FRAME_attack14        	83
#define BOSS2_FRAME_attack15        	84
#define BOSS2_FRAME_attack16        	85
#define BOSS2_FRAME_attack17        	86
#define BOSS2_FRAME_attack18        	87
#define BOSS2_FRAME_attack19        	88
#define BOSS2_FRAME_attack20        	89
#define BOSS2_FRAME_attack21        	90
#define BOSS2_FRAME_attack22        	91
#define BOSS2_FRAME_attack23        	92
#define BOSS2_FRAME_attack24        	93
#define BOSS2_FRAME_attack25        	94
#define BOSS2_FRAME_attack26        	95
#define BOSS2_FRAME_attack27        	96
#define BOSS2_FRAME_attack28        	97
#define BOSS2_FRAME_attack29        	98
#define BOSS2_FRAME_attack30        	99
#define BOSS2_FRAME_attack31        	100
#define BOSS2_FRAME_attack32        	101
#define BOSS2_FRAME_attack33        	102
#define BOSS2_FRAME_attack34        	103
#define BOSS2_FRAME_attack35        	104
#define BOSS2_FRAME_attack36        	105
#define BOSS2_FRAME_attack37        	106
#define BOSS2_FRAME_attack38        	107
#define BOSS2_FRAME_attack39        	108
#define BOSS2_FRAME_attack40        	109
#define BOSS2_FRAME_pain2           	110
#define BOSS2_FRAME_pain3           	111
#define BOSS2_FRAME_pain4           	112
#define BOSS2_FRAME_pain5           	113
#define BOSS2_FRAME_pain6           	114
#define BOSS2_FRAME_pain7           	115
#define BOSS2_FRAME_pain8           	116
#define BOSS2_FRAME_pain9           	117
#define BOSS2_FRAME_pain10          	118
#define BOSS2_FRAME_pain11          	119
#define BOSS2_FRAME_pain12          	120
#define BOSS2_FRAME_pain13          	121
#define BOSS2_FRAME_pain14          	122
#define BOSS2_FRAME_pain15          	123
#define BOSS2_FRAME_pain16          	124
#define BOSS2_FRAME_pain17          	125
#define BOSS2_FRAME_pain18          	126
#define BOSS2_FRAME_pain19          	127
#define BOSS2_FRAME_pain20          	128
#define BOSS2_FRAME_pain21          	129
#define BOSS2_FRAME_pain22          	130
#define BOSS2_FRAME_pain23          	131
#define BOSS2_FRAME_death2          	132
#define BOSS2_FRAME_death3          	133
#define BOSS2_FRAME_death4          	134
#define BOSS2_FRAME_death5          	135
#define BOSS2_FRAME_death6          	136
#define BOSS2_FRAME_death7          	137
#define BOSS2_FRAME_death8          	138
#define BOSS2_FRAME_death9          	139
#define BOSS2_FRAME_death10         	140
#define BOSS2_FRAME_death11         	141
#define BOSS2_FRAME_death12         	142
#define BOSS2_FRAME_death13         	143
#define BOSS2_FRAME_death14         	144
#define BOSS2_FRAME_death15         	145
#define BOSS2_FRAME_death16         	146
#define BOSS2_FRAME_death17         	147
#define BOSS2_FRAME_death18         	148
#define BOSS2_FRAME_death19         	149
#define BOSS2_FRAME_death20         	150
#define BOSS2_FRAME_death21         	151
#define BOSS2_FRAME_death22         	152
#define BOSS2_FRAME_death23         	153
#define BOSS2_FRAME_death24         	154
#define BOSS2_FRAME_death25         	155
#define BOSS2_FRAME_death26         	156
#define BOSS2_FRAME_death27         	157
#define BOSS2_FRAME_death28         	158
#define BOSS2_FRAME_death29         	159
#define BOSS2_FRAME_death30         	160
#define BOSS2_FRAME_death31         	161
#define BOSS2_FRAME_death32         	162
#define BOSS2_FRAME_death33         	163
#define BOSS2_FRAME_death34         	164
#define BOSS2_FRAME_death35         	165
#define BOSS2_FRAME_death36         	166
#define BOSS2_FRAME_death37         	167
#define BOSS2_FRAME_death38         	168
#define BOSS2_FRAME_death39         	169
#define BOSS2_FRAME_death40         	170
#define BOSS2_FRAME_death41         	171
#define BOSS2_FRAME_death42         	172
#define BOSS2_FRAME_death43         	173
#define BOSS2_FRAME_death44         	174
#define BOSS2_FRAME_death45         	175
#define BOSS2_FRAME_death46         	176
#define BOSS2_FRAME_death47         	177
#define BOSS2_FRAME_death48         	178
#define BOSS2_FRAME_death49         	179
#define BOSS2_FRAME_death50         	180

#define BOSS2_MODEL_SCALE		1.000000
