/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/brain

// This file generated by ModelGen - Do NOT Modify

#define BRAIN_FRAME_walk101         	0
#define BRAIN_FRAME_walk102         	1
#define BRAIN_FRAME_walk103         	2
#define BRAIN_FRAME_walk104         	3
#define BRAIN_FRAME_walk105         	4
#define BRAIN_FRAME_walk106         	5
#define BRAIN_FRAME_walk107         	6
#define BRAIN_FRAME_walk108         	7
#define BRAIN_FRAME_walk109         	8
#define BRAIN_FRAME_walk110         	9
#define BRAIN_FRAME_walk111         	10
#define BRAIN_FRAME_walk112         	11
#define BRAIN_FRAME_walk113         	12
#define BRAIN_FRAME_walk201         	13
#define BRAIN_FRAME_walk202         	14
#define BRAIN_FRAME_walk203         	15
#define BRAIN_FRAME_walk204         	16
#define BRAIN_FRAME_walk205         	17
#define BRAIN_FRAME_walk206         	18
#define BRAIN_FRAME_walk207         	19
#define BRAIN_FRAME_walk208         	20
#define BRAIN_FRAME_walk209         	21
#define BRAIN_FRAME_walk210         	22
#define BRAIN_FRAME_walk211         	23
#define BRAIN_FRAME_walk212         	24
#define BRAIN_FRAME_walk213         	25
#define BRAIN_FRAME_walk214         	26
#define BRAIN_FRAME_walk215         	27
#define BRAIN_FRAME_walk216         	28
#define BRAIN_FRAME_walk217         	29
#define BRAIN_FRAME_walk218         	30
#define BRAIN_FRAME_walk219         	31
#define BRAIN_FRAME_walk220         	32
#define BRAIN_FRAME_walk221         	33
#define BRAIN_FRAME_walk222         	34
#define BRAIN_FRAME_walk223         	35
#define BRAIN_FRAME_walk224         	36
#define BRAIN_FRAME_walk225         	37
#define BRAIN_FRAME_walk226         	38
#define BRAIN_FRAME_walk227         	39
#define BRAIN_FRAME_walk228         	40
#define BRAIN_FRAME_walk229         	41
#define BRAIN_FRAME_walk230         	42
#define BRAIN_FRAME_walk231         	43
#define BRAIN_FRAME_walk232         	44
#define BRAIN_FRAME_walk233         	45
#define BRAIN_FRAME_walk234         	46
#define BRAIN_FRAME_walk235         	47
#define BRAIN_FRAME_walk236         	48
#define BRAIN_FRAME_walk237         	49
#define BRAIN_FRAME_walk238         	50
#define BRAIN_FRAME_walk239         	51
#define BRAIN_FRAME_walk240         	52
#define BRAIN_FRAME_attak101        	53
#define BRAIN_FRAME_attak102        	54
#define BRAIN_FRAME_attak103        	55
#define BRAIN_FRAME_attak104        	56
#define BRAIN_FRAME_attak105        	57
#define BRAIN_FRAME_attak106        	58
#define BRAIN_FRAME_attak107        	59
#define BRAIN_FRAME_attak108        	60
#define BRAIN_FRAME_attak109        	61
#define BRAIN_FRAME_attak110        	62
#define BRAIN_FRAME_attak111        	63
#define BRAIN_FRAME_attak112        	64
#define BRAIN_FRAME_attak113        	65
#define BRAIN_FRAME_attak114        	66
#define BRAIN_FRAME_attak115        	67
#define BRAIN_FRAME_attak116        	68
#define BRAIN_FRAME_attak117        	69
#define BRAIN_FRAME_attak118        	70
#define BRAIN_FRAME_attak201        	71
#define BRAIN_FRAME_attak202        	72
#define BRAIN_FRAME_attak203        	73
#define BRAIN_FRAME_attak204        	74
#define BRAIN_FRAME_attak205        	75
#define BRAIN_FRAME_attak206        	76
#define BRAIN_FRAME_attak207        	77
#define BRAIN_FRAME_attak208        	78
#define BRAIN_FRAME_attak209        	79
#define BRAIN_FRAME_attak210        	80
#define BRAIN_FRAME_attak211        	81
#define BRAIN_FRAME_attak212        	82
#define BRAIN_FRAME_attak213        	83
#define BRAIN_FRAME_attak214        	84
#define BRAIN_FRAME_attak215        	85
#define BRAIN_FRAME_attak216        	86
#define BRAIN_FRAME_attak217        	87
#define BRAIN_FRAME_pain101         	88
#define BRAIN_FRAME_pain102         	89
#define BRAIN_FRAME_pain103         	90
#define BRAIN_FRAME_pain104         	91
#define BRAIN_FRAME_pain105         	92
#define BRAIN_FRAME_pain106         	93
#define BRAIN_FRAME_pain107         	94
#define BRAIN_FRAME_pain108         	95
#define BRAIN_FRAME_pain109         	96
#define BRAIN_FRAME_pain110         	97
#define BRAIN_FRAME_pain111         	98
#define BRAIN_FRAME_pain112         	99
#define BRAIN_FRAME_pain113         	100
#define BRAIN_FRAME_pain114         	101
#define BRAIN_FRAME_pain115         	102
#define BRAIN_FRAME_pain116         	103
#define BRAIN_FRAME_pain117         	104
#define BRAIN_FRAME_pain118         	105
#define BRAIN_FRAME_pain119         	106
#define BRAIN_FRAME_pain120         	107
#define BRAIN_FRAME_pain121         	108
#define BRAIN_FRAME_pain201         	109
#define BRAIN_FRAME_pain202         	110
#define BRAIN_FRAME_pain203         	111
#define BRAIN_FRAME_pain204         	112
#define BRAIN_FRAME_pain205         	113
#define BRAIN_FRAME_pain206         	114
#define BRAIN_FRAME_pain207         	115
#define BRAIN_FRAME_pain208         	116
#define BRAIN_FRAME_pain301         	117
#define BRAIN_FRAME_pain302         	118
#define BRAIN_FRAME_pain303         	119
#define BRAIN_FRAME_pain304         	120
#define BRAIN_FRAME_pain305         	121
#define BRAIN_FRAME_pain306         	122
#define BRAIN_FRAME_death101        	123
#define BRAIN_FRAME_death102        	124
#define BRAIN_FRAME_death103        	125
#define BRAIN_FRAME_death104        	126
#define BRAIN_FRAME_death105        	127
#define BRAIN_FRAME_death106        	128
#define BRAIN_FRAME_death107        	129
#define BRAIN_FRAME_death108        	130
#define BRAIN_FRAME_death109        	131
#define BRAIN_FRAME_death110        	132
#define BRAIN_FRAME_death111        	133
#define BRAIN_FRAME_death112        	134
#define BRAIN_FRAME_death113        	135
#define BRAIN_FRAME_death114        	136
#define BRAIN_FRAME_death115        	137
#define BRAIN_FRAME_death116        	138
#define BRAIN_FRAME_death117        	139
#define BRAIN_FRAME_death118        	140
#define BRAIN_FRAME_death201        	141
#define BRAIN_FRAME_death202        	142
#define BRAIN_FRAME_death203        	143
#define BRAIN_FRAME_death204        	144
#define BRAIN_FRAME_death205        	145
#define BRAIN_FRAME_duck01          	146
#define BRAIN_FRAME_duck02          	147
#define BRAIN_FRAME_duck03          	148
#define BRAIN_FRAME_duck04          	149
#define BRAIN_FRAME_duck05          	150
#define BRAIN_FRAME_duck06          	151
#define BRAIN_FRAME_duck07          	152
#define BRAIN_FRAME_duck08          	153
#define BRAIN_FRAME_defens01        	154
#define BRAIN_FRAME_defens02        	155
#define BRAIN_FRAME_defens03        	156
#define BRAIN_FRAME_defens04        	157
#define BRAIN_FRAME_defens05        	158
#define BRAIN_FRAME_defens06        	159
#define BRAIN_FRAME_defens07        	160
#define BRAIN_FRAME_defens08        	161
#define BRAIN_FRAME_stand01         	162
#define BRAIN_FRAME_stand02         	163
#define BRAIN_FRAME_stand03         	164
#define BRAIN_FRAME_stand04         	165
#define BRAIN_FRAME_stand05         	166
#define BRAIN_FRAME_stand06         	167
#define BRAIN_FRAME_stand07         	168
#define BRAIN_FRAME_stand08         	169
#define BRAIN_FRAME_stand09         	170
#define BRAIN_FRAME_stand10         	171
#define BRAIN_FRAME_stand11         	172
#define BRAIN_FRAME_stand12         	173
#define BRAIN_FRAME_stand13         	174
#define BRAIN_FRAME_stand14         	175
#define BRAIN_FRAME_stand15         	176
#define BRAIN_FRAME_stand16         	177
#define BRAIN_FRAME_stand17         	178
#define BRAIN_FRAME_stand18         	179
#define BRAIN_FRAME_stand19         	180
#define BRAIN_FRAME_stand20         	181
#define BRAIN_FRAME_stand21         	182
#define BRAIN_FRAME_stand22         	183
#define BRAIN_FRAME_stand23         	184
#define BRAIN_FRAME_stand24         	185
#define BRAIN_FRAME_stand25         	186
#define BRAIN_FRAME_stand26         	187
#define BRAIN_FRAME_stand27         	188
#define BRAIN_FRAME_stand28         	189
#define BRAIN_FRAME_stand29         	190
#define BRAIN_FRAME_stand30         	191
#define BRAIN_FRAME_stand31         	192
#define BRAIN_FRAME_stand32         	193
#define BRAIN_FRAME_stand33         	194
#define BRAIN_FRAME_stand34         	195
#define BRAIN_FRAME_stand35         	196
#define BRAIN_FRAME_stand36         	197
#define BRAIN_FRAME_stand37         	198
#define BRAIN_FRAME_stand38         	199
#define BRAIN_FRAME_stand39         	200
#define BRAIN_FRAME_stand40         	201
#define BRAIN_FRAME_stand41         	202
#define BRAIN_FRAME_stand42         	203
#define BRAIN_FRAME_stand43         	204
#define BRAIN_FRAME_stand44         	205
#define BRAIN_FRAME_stand45         	206
#define BRAIN_FRAME_stand46         	207
#define BRAIN_FRAME_stand47         	208
#define BRAIN_FRAME_stand48         	209
#define BRAIN_FRAME_stand49         	210
#define BRAIN_FRAME_stand50         	211
#define BRAIN_FRAME_stand51         	212
#define BRAIN_FRAME_stand52         	213
#define BRAIN_FRAME_stand53         	214
#define BRAIN_FRAME_stand54         	215
#define BRAIN_FRAME_stand55         	216
#define BRAIN_FRAME_stand56         	217
#define BRAIN_FRAME_stand57         	218
#define BRAIN_FRAME_stand58         	219
#define BRAIN_FRAME_stand59         	220
#define BRAIN_FRAME_stand60         	221

#define BRAIN_MODEL_SCALE		1.000000
