/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/flipper

// This file generated by ModelGen - Do NOT Modify

#define FLIPPER_FRAME_flpbit01        	0
#define FLIPPER_FRAME_flpbit02        	1
#define FLIPPER_FRAME_flpbit03        	2
#define FLIPPER_FRAME_flpbit04        	3
#define FLIPPER_FRAME_flpbit05        	4
#define FLIPPER_FRAME_flpbit06        	5
#define FLIPPER_FRAME_flpbit07        	6
#define FLIPPER_FRAME_flpbit08        	7
#define FLIPPER_FRAME_flpbit09        	8
#define FLIPPER_FRAME_flpbit10        	9
#define FLIPPER_FRAME_flpbit11        	10
#define FLIPPER_FRAME_flpbit12        	11
#define FLIPPER_FRAME_flpbit13        	12
#define FLIPPER_FRAME_flpbit14        	13
#define FLIPPER_FRAME_flpbit15        	14
#define FLIPPER_FRAME_flpbit16        	15
#define FLIPPER_FRAME_flpbit17        	16
#define FLIPPER_FRAME_flpbit18        	17
#define FLIPPER_FRAME_flpbit19        	18
#define FLIPPER_FRAME_flpbit20        	19
#define FLIPPER_FRAME_flptal01        	20
#define FLIPPER_FRAME_flptal02        	21
#define FLIPPER_FRAME_flptal03        	22
#define FLIPPER_FRAME_flptal04        	23
#define FLIPPER_FRAME_flptal05        	24
#define FLIPPER_FRAME_flptal06        	25
#define FLIPPER_FRAME_flptal07        	26
#define FLIPPER_FRAME_flptal08        	27
#define FLIPPER_FRAME_flptal09        	28
#define FLIPPER_FRAME_flptal10        	29
#define FLIPPER_FRAME_flptal11        	30
#define FLIPPER_FRAME_flptal12        	31
#define FLIPPER_FRAME_flptal13        	32
#define FLIPPER_FRAME_flptal14        	33
#define FLIPPER_FRAME_flptal15        	34
#define FLIPPER_FRAME_flptal16        	35
#define FLIPPER_FRAME_flptal17        	36
#define FLIPPER_FRAME_flptal18        	37
#define FLIPPER_FRAME_flptal19        	38
#define FLIPPER_FRAME_flptal20        	39
#define FLIPPER_FRAME_flptal21        	40
#define FLIPPER_FRAME_flphor01        	41
#define FLIPPER_FRAME_flphor02        	42
#define FLIPPER_FRAME_flphor03        	43
#define FLIPPER_FRAME_flphor04        	44
#define FLIPPER_FRAME_flphor05        	45
#define FLIPPER_FRAME_flphor06        	46
#define FLIPPER_FRAME_flphor07        	47
#define FLIPPER_FRAME_flphor08        	48
#define FLIPPER_FRAME_flphor09        	49
#define FLIPPER_FRAME_flphor10        	50
#define FLIPPER_FRAME_flphor11        	51
#define FLIPPER_FRAME_flphor12        	52
#define FLIPPER_FRAME_flphor13        	53
#define FLIPPER_FRAME_flphor14        	54
#define FLIPPER_FRAME_flphor15        	55
#define FLIPPER_FRAME_flphor16        	56
#define FLIPPER_FRAME_flphor17        	57
#define FLIPPER_FRAME_flphor18        	58
#define FLIPPER_FRAME_flphor19        	59
#define FLIPPER_FRAME_flphor20        	60
#define FLIPPER_FRAME_flphor21        	61
#define FLIPPER_FRAME_flphor22        	62
#define FLIPPER_FRAME_flphor23        	63
#define FLIPPER_FRAME_flphor24        	64
#define FLIPPER_FRAME_flpver01        	65
#define FLIPPER_FRAME_flpver02        	66
#define FLIPPER_FRAME_flpver03        	67
#define FLIPPER_FRAME_flpver04        	68
#define FLIPPER_FRAME_flpver05        	69
#define FLIPPER_FRAME_flpver06        	70
#define FLIPPER_FRAME_flpver07        	71
#define FLIPPER_FRAME_flpver08        	72
#define FLIPPER_FRAME_flpver09        	73
#define FLIPPER_FRAME_flpver10        	74
#define FLIPPER_FRAME_flpver11        	75
#define FLIPPER_FRAME_flpver12        	76
#define FLIPPER_FRAME_flpver13        	77
#define FLIPPER_FRAME_flpver14        	78
#define FLIPPER_FRAME_flpver15        	79
#define FLIPPER_FRAME_flpver16        	80
#define FLIPPER_FRAME_flpver17        	81
#define FLIPPER_FRAME_flpver18        	82
#define FLIPPER_FRAME_flpver19        	83
#define FLIPPER_FRAME_flpver20        	84
#define FLIPPER_FRAME_flpver21        	85
#define FLIPPER_FRAME_flpver22        	86
#define FLIPPER_FRAME_flpver23        	87
#define FLIPPER_FRAME_flpver24        	88
#define FLIPPER_FRAME_flpver25        	89
#define FLIPPER_FRAME_flpver26        	90
#define FLIPPER_FRAME_flpver27        	91
#define FLIPPER_FRAME_flpver28        	92
#define FLIPPER_FRAME_flpver29        	93
#define FLIPPER_FRAME_flppn101        	94
#define FLIPPER_FRAME_flppn102        	95
#define FLIPPER_FRAME_flppn103        	96
#define FLIPPER_FRAME_flppn104        	97
#define FLIPPER_FRAME_flppn105        	98
#define FLIPPER_FRAME_flppn201        	99
#define FLIPPER_FRAME_flppn202        	100
#define FLIPPER_FRAME_flppn203        	101
#define FLIPPER_FRAME_flppn204        	102
#define FLIPPER_FRAME_flppn205        	103
#define FLIPPER_FRAME_flpdth01        	104
#define FLIPPER_FRAME_flpdth02        	105
#define FLIPPER_FRAME_flpdth03        	106
#define FLIPPER_FRAME_flpdth04        	107
#define FLIPPER_FRAME_flpdth05        	108
#define FLIPPER_FRAME_flpdth06        	109
#define FLIPPER_FRAME_flpdth07        	110
#define FLIPPER_FRAME_flpdth08        	111
#define FLIPPER_FRAME_flpdth09        	112
#define FLIPPER_FRAME_flpdth10        	113
#define FLIPPER_FRAME_flpdth11        	114
#define FLIPPER_FRAME_flpdth12        	115
#define FLIPPER_FRAME_flpdth13        	116
#define FLIPPER_FRAME_flpdth14        	117
#define FLIPPER_FRAME_flpdth15        	118
#define FLIPPER_FRAME_flpdth16        	119
#define FLIPPER_FRAME_flpdth17        	120
#define FLIPPER_FRAME_flpdth18        	121
#define FLIPPER_FRAME_flpdth19        	122
#define FLIPPER_FRAME_flpdth20        	123
#define FLIPPER_FRAME_flpdth21        	124
#define FLIPPER_FRAME_flpdth22        	125
#define FLIPPER_FRAME_flpdth23        	126
#define FLIPPER_FRAME_flpdth24        	127
#define FLIPPER_FRAME_flpdth25        	128
#define FLIPPER_FRAME_flpdth26        	129
#define FLIPPER_FRAME_flpdth27        	130
#define FLIPPER_FRAME_flpdth28        	131
#define FLIPPER_FRAME_flpdth29        	132
#define FLIPPER_FRAME_flpdth30        	133
#define FLIPPER_FRAME_flpdth31        	134
#define FLIPPER_FRAME_flpdth32        	135
#define FLIPPER_FRAME_flpdth33        	136
#define FLIPPER_FRAME_flpdth34        	137
#define FLIPPER_FRAME_flpdth35        	138
#define FLIPPER_FRAME_flpdth36        	139
#define FLIPPER_FRAME_flpdth37        	140
#define FLIPPER_FRAME_flpdth38        	141
#define FLIPPER_FRAME_flpdth39        	142
#define FLIPPER_FRAME_flpdth40        	143
#define FLIPPER_FRAME_flpdth41        	144
#define FLIPPER_FRAME_flpdth42        	145
#define FLIPPER_FRAME_flpdth43        	146
#define FLIPPER_FRAME_flpdth44        	147
#define FLIPPER_FRAME_flpdth45        	148
#define FLIPPER_FRAME_flpdth46        	149
#define FLIPPER_FRAME_flpdth47        	150
#define FLIPPER_FRAME_flpdth48        	151
#define FLIPPER_FRAME_flpdth49        	152
#define FLIPPER_FRAME_flpdth50        	153
#define FLIPPER_FRAME_flpdth51        	154
#define FLIPPER_FRAME_flpdth52        	155
#define FLIPPER_FRAME_flpdth53        	156
#define FLIPPER_FRAME_flpdth54        	157
#define FLIPPER_FRAME_flpdth55        	158
#define FLIPPER_FRAME_flpdth56        	159

#define FLIPPER_MODEL_SCALE		1.000000
