/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/gladiatr

// This file generated by ModelGen - Do NOT Modify

#define GLADIATOR_FRAME_stand1          	0
#define GLADIATOR_FRAME_stand2          	1
#define GLADIATOR_FRAME_stand3          	2
#define GLADIATOR_FRAME_stand4          	3
#define GLADIATOR_FRAME_stand5          	4
#define GLADIATOR_FRAME_stand6          	5
#define GLADIATOR_FRAME_stand7          	6
#define GLADIATOR_FRAME_walk1           	7
#define GLADIATOR_FRAME_walk2           	8
#define GLADIATOR_FRAME_walk3           	9
#define GLADIATOR_FRAME_walk4           	10
#define GLADIATOR_FRAME_walk5           	11
#define GLADIATOR_FRAME_walk6           	12
#define GLADIATOR_FRAME_walk7           	13
#define GLADIATOR_FRAME_walk8           	14
#define GLADIATOR_FRAME_walk9           	15
#define GLADIATOR_FRAME_walk10          	16
#define GLADIATOR_FRAME_walk11          	17
#define GLADIATOR_FRAME_walk12          	18
#define GLADIATOR_FRAME_walk13          	19
#define GLADIATOR_FRAME_walk14          	20
#define GLADIATOR_FRAME_walk15          	21
#define GLADIATOR_FRAME_walk16          	22
#define GLADIATOR_FRAME_run1            	23
#define GLADIATOR_FRAME_run2            	24
#define GLADIATOR_FRAME_run3            	25
#define GLADIATOR_FRAME_run4            	26
#define GLADIATOR_FRAME_run5            	27
#define GLADIATOR_FRAME_run6            	28
#define GLADIATOR_FRAME_melee1          	29
#define GLADIATOR_FRAME_melee2          	30
#define GLADIATOR_FRAME_melee3          	31
#define GLADIATOR_FRAME_melee4          	32
#define GLADIATOR_FRAME_melee5          	33
#define GLADIATOR_FRAME_melee6          	34
#define GLADIATOR_FRAME_melee7          	35
#define GLADIATOR_FRAME_melee8          	36
#define GLADIATOR_FRAME_melee9          	37
#define GLADIATOR_FRAME_melee10         	38
#define GLADIATOR_FRAME_melee11         	39
#define GLADIATOR_FRAME_melee12         	40
#define GLADIATOR_FRAME_melee13         	41
#define GLADIATOR_FRAME_melee14         	42
#define GLADIATOR_FRAME_melee15         	43
#define GLADIATOR_FRAME_melee16         	44
#define GLADIATOR_FRAME_melee17         	45
#define GLADIATOR_FRAME_attack1         	46
#define GLADIATOR_FRAME_attack2         	47
#define GLADIATOR_FRAME_attack3         	48
#define GLADIATOR_FRAME_attack4         	49
#define GLADIATOR_FRAME_attack5         	50
#define GLADIATOR_FRAME_attack6         	51
#define GLADIATOR_FRAME_attack7         	52
#define GLADIATOR_FRAME_attack8         	53
#define GLADIATOR_FRAME_attack9         	54
#define GLADIATOR_FRAME_pain1           	55
#define GLADIATOR_FRAME_pain2           	56
#define GLADIATOR_FRAME_pain3           	57
#define GLADIATOR_FRAME_pain4           	58
#define GLADIATOR_FRAME_pain5           	59
#define GLADIATOR_FRAME_pain6           	60
#define GLADIATOR_FRAME_death1          	61
#define GLADIATOR_FRAME_death2          	62
#define GLADIATOR_FRAME_death3          	63
#define GLADIATOR_FRAME_death4          	64
#define GLADIATOR_FRAME_death5          	65
#define GLADIATOR_FRAME_death6          	66
#define GLADIATOR_FRAME_death7          	67
#define GLADIATOR_FRAME_death8          	68
#define GLADIATOR_FRAME_death9          	69
#define GLADIATOR_FRAME_death10         	70
#define GLADIATOR_FRAME_death11         	71
#define GLADIATOR_FRAME_death12         	72
#define GLADIATOR_FRAME_death13         	73
#define GLADIATOR_FRAME_death14         	74
#define GLADIATOR_FRAME_death15         	75
#define GLADIATOR_FRAME_death16         	76
#define GLADIATOR_FRAME_death17         	77
#define GLADIATOR_FRAME_death18         	78
#define GLADIATOR_FRAME_death19         	79
#define GLADIATOR_FRAME_death20         	80
#define GLADIATOR_FRAME_death21         	81
#define GLADIATOR_FRAME_death22         	82
#define GLADIATOR_FRAME_painup1         	83
#define GLADIATOR_FRAME_painup2         	84
#define GLADIATOR_FRAME_painup3         	85
#define GLADIATOR_FRAME_painup4         	86
#define GLADIATOR_FRAME_painup5         	87
#define GLADIATOR_FRAME_painup6         	88
#define GLADIATOR_FRAME_painup7         	89

#define GLADIATOR_MODEL_SCALE		1.000000
