/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/gunner

// This file generated by ModelGen - Do NOT Modify

#define GUNNER_FRAME_stand01         	0
#define GUNNER_FRAME_stand02         	1
#define GUNNER_FRAME_stand03         	2
#define GUNNER_FRAME_stand04         	3
#define GUNNER_FRAME_stand05         	4
#define GUNNER_FRAME_stand06         	5
#define GUNNER_FRAME_stand07         	6
#define GUNNER_FRAME_stand08         	7
#define GUNNER_FRAME_stand09         	8
#define GUNNER_FRAME_stand10         	9
#define GUNNER_FRAME_stand11         	10
#define GUNNER_FRAME_stand12         	11
#define GUNNER_FRAME_stand13         	12
#define GUNNER_FRAME_stand14         	13
#define GUNNER_FRAME_stand15         	14
#define GUNNER_FRAME_stand16         	15
#define GUNNER_FRAME_stand17         	16
#define GUNNER_FRAME_stand18         	17
#define GUNNER_FRAME_stand19         	18
#define GUNNER_FRAME_stand20         	19
#define GUNNER_FRAME_stand21         	20
#define GUNNER_FRAME_stand22         	21
#define GUNNER_FRAME_stand23         	22
#define GUNNER_FRAME_stand24         	23
#define GUNNER_FRAME_stand25         	24
#define GUNNER_FRAME_stand26         	25
#define GUNNER_FRAME_stand27         	26
#define GUNNER_FRAME_stand28         	27
#define GUNNER_FRAME_stand29         	28
#define GUNNER_FRAME_stand30         	29
#define GUNNER_FRAME_stand31         	30
#define GUNNER_FRAME_stand32         	31
#define GUNNER_FRAME_stand33         	32
#define GUNNER_FRAME_stand34         	33
#define GUNNER_FRAME_stand35         	34
#define GUNNER_FRAME_stand36         	35
#define GUNNER_FRAME_stand37         	36
#define GUNNER_FRAME_stand38         	37
#define GUNNER_FRAME_stand39         	38
#define GUNNER_FRAME_stand40         	39
#define GUNNER_FRAME_stand41         	40
#define GUNNER_FRAME_stand42         	41
#define GUNNER_FRAME_stand43         	42
#define GUNNER_FRAME_stand44         	43
#define GUNNER_FRAME_stand45         	44
#define GUNNER_FRAME_stand46         	45
#define GUNNER_FRAME_stand47         	46
#define GUNNER_FRAME_stand48         	47
#define GUNNER_FRAME_stand49         	48
#define GUNNER_FRAME_stand50         	49
#define GUNNER_FRAME_stand51         	50
#define GUNNER_FRAME_stand52         	51
#define GUNNER_FRAME_stand53         	52
#define GUNNER_FRAME_stand54         	53
#define GUNNER_FRAME_stand55         	54
#define GUNNER_FRAME_stand56         	55
#define GUNNER_FRAME_stand57         	56
#define GUNNER_FRAME_stand58         	57
#define GUNNER_FRAME_stand59         	58
#define GUNNER_FRAME_stand60         	59
#define GUNNER_FRAME_stand61         	60
#define GUNNER_FRAME_stand62         	61
#define GUNNER_FRAME_stand63         	62
#define GUNNER_FRAME_stand64         	63
#define GUNNER_FRAME_stand65         	64
#define GUNNER_FRAME_stand66         	65
#define GUNNER_FRAME_stand67         	66
#define GUNNER_FRAME_stand68         	67
#define GUNNER_FRAME_stand69         	68
#define GUNNER_FRAME_stand70         	69
#define GUNNER_FRAME_walk01          	70
#define GUNNER_FRAME_walk02          	71
#define GUNNER_FRAME_walk03          	72
#define GUNNER_FRAME_walk04          	73
#define GUNNER_FRAME_walk05          	74
#define GUNNER_FRAME_walk06          	75
#define GUNNER_FRAME_walk07          	76
#define GUNNER_FRAME_walk08          	77
#define GUNNER_FRAME_walk09          	78
#define GUNNER_FRAME_walk10          	79
#define GUNNER_FRAME_walk11          	80
#define GUNNER_FRAME_walk12          	81
#define GUNNER_FRAME_walk13          	82
#define GUNNER_FRAME_walk14          	83
#define GUNNER_FRAME_walk15          	84
#define GUNNER_FRAME_walk16          	85
#define GUNNER_FRAME_walk17          	86
#define GUNNER_FRAME_walk18          	87
#define GUNNER_FRAME_walk19          	88
#define GUNNER_FRAME_walk20          	89
#define GUNNER_FRAME_walk21          	90
#define GUNNER_FRAME_walk22          	91
#define GUNNER_FRAME_walk23          	92
#define GUNNER_FRAME_walk24          	93
#define GUNNER_FRAME_run01           	94
#define GUNNER_FRAME_run02           	95
#define GUNNER_FRAME_run03           	96
#define GUNNER_FRAME_run04           	97
#define GUNNER_FRAME_run05           	98
#define GUNNER_FRAME_run06           	99
#define GUNNER_FRAME_run07           	100
#define GUNNER_FRAME_run08           	101
#define GUNNER_FRAME_runs01          	102
#define GUNNER_FRAME_runs02          	103
#define GUNNER_FRAME_runs03          	104
#define GUNNER_FRAME_runs04          	105
#define GUNNER_FRAME_runs05          	106
#define GUNNER_FRAME_runs06          	107
#define GUNNER_FRAME_attak101        	108
#define GUNNER_FRAME_attak102        	109
#define GUNNER_FRAME_attak103        	110
#define GUNNER_FRAME_attak104        	111
#define GUNNER_FRAME_attak105        	112
#define GUNNER_FRAME_attak106        	113
#define GUNNER_FRAME_attak107        	114
#define GUNNER_FRAME_attak108        	115
#define GUNNER_FRAME_attak109        	116
#define GUNNER_FRAME_attak110        	117
#define GUNNER_FRAME_attak111        	118
#define GUNNER_FRAME_attak112        	119
#define GUNNER_FRAME_attak113        	120
#define GUNNER_FRAME_attak114        	121
#define GUNNER_FRAME_attak115        	122
#define GUNNER_FRAME_attak116        	123
#define GUNNER_FRAME_attak117        	124
#define GUNNER_FRAME_attak118        	125
#define GUNNER_FRAME_attak119        	126
#define GUNNER_FRAME_attak120        	127
#define GUNNER_FRAME_attak121        	128
#define GUNNER_FRAME_attak201        	129
#define GUNNER_FRAME_attak202        	130
#define GUNNER_FRAME_attak203        	131
#define GUNNER_FRAME_attak204        	132
#define GUNNER_FRAME_attak205        	133
#define GUNNER_FRAME_attak206        	134
#define GUNNER_FRAME_attak207        	135
#define GUNNER_FRAME_attak208        	136
#define GUNNER_FRAME_attak209        	137
#define GUNNER_FRAME_attak210        	138
#define GUNNER_FRAME_attak211        	139
#define GUNNER_FRAME_attak212        	140
#define GUNNER_FRAME_attak213        	141
#define GUNNER_FRAME_attak214        	142
#define GUNNER_FRAME_attak215        	143
#define GUNNER_FRAME_attak216        	144
#define GUNNER_FRAME_attak217        	145
#define GUNNER_FRAME_attak218        	146
#define GUNNER_FRAME_attak219        	147
#define GUNNER_FRAME_attak220        	148
#define GUNNER_FRAME_attak221        	149
#define GUNNER_FRAME_attak222        	150
#define GUNNER_FRAME_attak223        	151
#define GUNNER_FRAME_attak224        	152
#define GUNNER_FRAME_attak225        	153
#define GUNNER_FRAME_attak226        	154
#define GUNNER_FRAME_attak227        	155
#define GUNNER_FRAME_attak228        	156
#define GUNNER_FRAME_attak229        	157
#define GUNNER_FRAME_attak230        	158
#define GUNNER_FRAME_pain101         	159
#define GUNNER_FRAME_pain102         	160
#define GUNNER_FRAME_pain103         	161
#define GUNNER_FRAME_pain104         	162
#define GUNNER_FRAME_pain105         	163
#define GUNNER_FRAME_pain106         	164
#define GUNNER_FRAME_pain107         	165
#define GUNNER_FRAME_pain108         	166
#define GUNNER_FRAME_pain109         	167
#define GUNNER_FRAME_pain110         	168
#define GUNNER_FRAME_pain111         	169
#define GUNNER_FRAME_pain112         	170
#define GUNNER_FRAME_pain113         	171
#define GUNNER_FRAME_pain114         	172
#define GUNNER_FRAME_pain115         	173
#define GUNNER_FRAME_pain116         	174
#define GUNNER_FRAME_pain117         	175
#define GUNNER_FRAME_pain118         	176
#define GUNNER_FRAME_pain201         	177
#define GUNNER_FRAME_pain202         	178
#define GUNNER_FRAME_pain203         	179
#define GUNNER_FRAME_pain204         	180
#define GUNNER_FRAME_pain205         	181
#define GUNNER_FRAME_pain206         	182
#define GUNNER_FRAME_pain207         	183
#define GUNNER_FRAME_pain208         	184
#define GUNNER_FRAME_pain301         	185
#define GUNNER_FRAME_pain302         	186
#define GUNNER_FRAME_pain303         	187
#define GUNNER_FRAME_pain304         	188
#define GUNNER_FRAME_pain305         	189
#define GUNNER_FRAME_death01         	190
#define GUNNER_FRAME_death02         	191
#define GUNNER_FRAME_death03         	192
#define GUNNER_FRAME_death04         	193
#define GUNNER_FRAME_death05         	194
#define GUNNER_FRAME_death06         	195
#define GUNNER_FRAME_death07         	196
#define GUNNER_FRAME_death08         	197
#define GUNNER_FRAME_death09         	198
#define GUNNER_FRAME_death10         	199
#define GUNNER_FRAME_death11         	200
#define GUNNER_FRAME_duck01          	201
#define GUNNER_FRAME_duck02          	202
#define GUNNER_FRAME_duck03          	203
#define GUNNER_FRAME_duck04          	204
#define GUNNER_FRAME_duck05          	205
#define GUNNER_FRAME_duck06          	206
#define GUNNER_FRAME_duck07          	207
#define GUNNER_FRAME_duck08          	208

#define GUNNER_MODEL_SCALE		1.150000
