/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/hover

// This file generated by ModelGen - Do NOT Modify

#define HOVER_FRAME_stand01         	0
#define HOVER_FRAME_stand02         	1
#define HOVER_FRAME_stand03         	2
#define HOVER_FRAME_stand04         	3
#define HOVER_FRAME_stand05         	4
#define HOVER_FRAME_stand06         	5
#define HOVER_FRAME_stand07         	6
#define HOVER_FRAME_stand08         	7
#define HOVER_FRAME_stand09         	8
#define HOVER_FRAME_stand10         	9
#define HOVER_FRAME_stand11         	10
#define HOVER_FRAME_stand12         	11
#define HOVER_FRAME_stand13         	12
#define HOVER_FRAME_stand14         	13
#define HOVER_FRAME_stand15         	14
#define HOVER_FRAME_stand16         	15
#define HOVER_FRAME_stand17         	16
#define HOVER_FRAME_stand18         	17
#define HOVER_FRAME_stand19         	18
#define HOVER_FRAME_stand20         	19
#define HOVER_FRAME_stand21         	20
#define HOVER_FRAME_stand22         	21
#define HOVER_FRAME_stand23         	22
#define HOVER_FRAME_stand24         	23
#define HOVER_FRAME_stand25         	24
#define HOVER_FRAME_stand26         	25
#define HOVER_FRAME_stand27         	26
#define HOVER_FRAME_stand28         	27
#define HOVER_FRAME_stand29         	28
#define HOVER_FRAME_stand30         	29
#define HOVER_FRAME_forwrd01        	30
#define HOVER_FRAME_forwrd02        	31
#define HOVER_FRAME_forwrd03        	32
#define HOVER_FRAME_forwrd04        	33
#define HOVER_FRAME_forwrd05        	34
#define HOVER_FRAME_forwrd06        	35
#define HOVER_FRAME_forwrd07        	36
#define HOVER_FRAME_forwrd08        	37
#define HOVER_FRAME_forwrd09        	38
#define HOVER_FRAME_forwrd10        	39
#define HOVER_FRAME_forwrd11        	40
#define HOVER_FRAME_forwrd12        	41
#define HOVER_FRAME_forwrd13        	42
#define HOVER_FRAME_forwrd14        	43
#define HOVER_FRAME_forwrd15        	44
#define HOVER_FRAME_forwrd16        	45
#define HOVER_FRAME_forwrd17        	46
#define HOVER_FRAME_forwrd18        	47
#define HOVER_FRAME_forwrd19        	48
#define HOVER_FRAME_forwrd20        	49
#define HOVER_FRAME_forwrd21        	50
#define HOVER_FRAME_forwrd22        	51
#define HOVER_FRAME_forwrd23        	52
#define HOVER_FRAME_forwrd24        	53
#define HOVER_FRAME_forwrd25        	54
#define HOVER_FRAME_forwrd26        	55
#define HOVER_FRAME_forwrd27        	56
#define HOVER_FRAME_forwrd28        	57
#define HOVER_FRAME_forwrd29        	58
#define HOVER_FRAME_forwrd30        	59
#define HOVER_FRAME_forwrd31        	60
#define HOVER_FRAME_forwrd32        	61
#define HOVER_FRAME_forwrd33        	62
#define HOVER_FRAME_forwrd34        	63
#define HOVER_FRAME_forwrd35        	64
#define HOVER_FRAME_stop101         	65
#define HOVER_FRAME_stop102         	66
#define HOVER_FRAME_stop103         	67
#define HOVER_FRAME_stop104         	68
#define HOVER_FRAME_stop105         	69
#define HOVER_FRAME_stop106         	70
#define HOVER_FRAME_stop107         	71
#define HOVER_FRAME_stop108         	72
#define HOVER_FRAME_stop109         	73
#define HOVER_FRAME_stop201         	74
#define HOVER_FRAME_stop202         	75
#define HOVER_FRAME_stop203         	76
#define HOVER_FRAME_stop204         	77
#define HOVER_FRAME_stop205         	78
#define HOVER_FRAME_stop206         	79
#define HOVER_FRAME_stop207         	80
#define HOVER_FRAME_stop208         	81
#define HOVER_FRAME_takeof01        	82
#define HOVER_FRAME_takeof02        	83
#define HOVER_FRAME_takeof03        	84
#define HOVER_FRAME_takeof04        	85
#define HOVER_FRAME_takeof05        	86
#define HOVER_FRAME_takeof06        	87
#define HOVER_FRAME_takeof07        	88
#define HOVER_FRAME_takeof08        	89
#define HOVER_FRAME_takeof09        	90
#define HOVER_FRAME_takeof10        	91
#define HOVER_FRAME_takeof11        	92
#define HOVER_FRAME_takeof12        	93
#define HOVER_FRAME_takeof13        	94
#define HOVER_FRAME_takeof14        	95
#define HOVER_FRAME_takeof15        	96
#define HOVER_FRAME_takeof16        	97
#define HOVER_FRAME_takeof17        	98
#define HOVER_FRAME_takeof18        	99
#define HOVER_FRAME_takeof19        	100
#define HOVER_FRAME_takeof20        	101
#define HOVER_FRAME_takeof21        	102
#define HOVER_FRAME_takeof22        	103
#define HOVER_FRAME_takeof23        	104
#define HOVER_FRAME_takeof24        	105
#define HOVER_FRAME_takeof25        	106
#define HOVER_FRAME_takeof26        	107
#define HOVER_FRAME_takeof27        	108
#define HOVER_FRAME_takeof28        	109
#define HOVER_FRAME_takeof29        	110
#define HOVER_FRAME_takeof30        	111
#define HOVER_FRAME_land01          	112
#define HOVER_FRAME_pain101         	113
#define HOVER_FRAME_pain102         	114
#define HOVER_FRAME_pain103         	115
#define HOVER_FRAME_pain104         	116
#define HOVER_FRAME_pain105         	117
#define HOVER_FRAME_pain106         	118
#define HOVER_FRAME_pain107         	119
#define HOVER_FRAME_pain108         	120
#define HOVER_FRAME_pain109         	121
#define HOVER_FRAME_pain110         	122
#define HOVER_FRAME_pain111         	123
#define HOVER_FRAME_pain112         	124
#define HOVER_FRAME_pain113         	125
#define HOVER_FRAME_pain114         	126
#define HOVER_FRAME_pain115         	127
#define HOVER_FRAME_pain116         	128
#define HOVER_FRAME_pain117         	129
#define HOVER_FRAME_pain118         	130
#define HOVER_FRAME_pain119         	131
#define HOVER_FRAME_pain120         	132
#define HOVER_FRAME_pain121         	133
#define HOVER_FRAME_pain122         	134
#define HOVER_FRAME_pain123         	135
#define HOVER_FRAME_pain124         	136
#define HOVER_FRAME_pain125         	137
#define HOVER_FRAME_pain126         	138
#define HOVER_FRAME_pain127         	139
#define HOVER_FRAME_pain128         	140
#define HOVER_FRAME_pain201         	141
#define HOVER_FRAME_pain202         	142
#define HOVER_FRAME_pain203         	143
#define HOVER_FRAME_pain204         	144
#define HOVER_FRAME_pain205         	145
#define HOVER_FRAME_pain206         	146
#define HOVER_FRAME_pain207         	147
#define HOVER_FRAME_pain208         	148
#define HOVER_FRAME_pain209         	149
#define HOVER_FRAME_pain210         	150
#define HOVER_FRAME_pain211         	151
#define HOVER_FRAME_pain212         	152
#define HOVER_FRAME_pain301         	153
#define HOVER_FRAME_pain302         	154
#define HOVER_FRAME_pain303         	155
#define HOVER_FRAME_pain304         	156
#define HOVER_FRAME_pain305         	157
#define HOVER_FRAME_pain306         	158
#define HOVER_FRAME_pain307         	159
#define HOVER_FRAME_pain308         	160
#define HOVER_FRAME_pain309         	161
#define HOVER_FRAME_death101        	162
#define HOVER_FRAME_death102        	163
#define HOVER_FRAME_death103        	164
#define HOVER_FRAME_death104        	165
#define HOVER_FRAME_death105        	166
#define HOVER_FRAME_death106        	167
#define HOVER_FRAME_death107        	168
#define HOVER_FRAME_death108        	169
#define HOVER_FRAME_death109        	170
#define HOVER_FRAME_death110        	171
#define HOVER_FRAME_death111        	172
#define HOVER_FRAME_backwd01        	173
#define HOVER_FRAME_backwd02        	174
#define HOVER_FRAME_backwd03        	175
#define HOVER_FRAME_backwd04        	176
#define HOVER_FRAME_backwd05        	177
#define HOVER_FRAME_backwd06        	178
#define HOVER_FRAME_backwd07        	179
#define HOVER_FRAME_backwd08        	180
#define HOVER_FRAME_backwd09        	181
#define HOVER_FRAME_backwd10        	182
#define HOVER_FRAME_backwd11        	183
#define HOVER_FRAME_backwd12        	184
#define HOVER_FRAME_backwd13        	185
#define HOVER_FRAME_backwd14        	186
#define HOVER_FRAME_backwd15        	187
#define HOVER_FRAME_backwd16        	188
#define HOVER_FRAME_backwd17        	189
#define HOVER_FRAME_backwd18        	190
#define HOVER_FRAME_backwd19        	191
#define HOVER_FRAME_backwd20        	192
#define HOVER_FRAME_backwd21        	193
#define HOVER_FRAME_backwd22        	194
#define HOVER_FRAME_backwd23        	195
#define HOVER_FRAME_backwd24        	196
#define HOVER_FRAME_attak101        	197
#define HOVER_FRAME_attak102        	198
#define HOVER_FRAME_attak103        	199
#define HOVER_FRAME_attak104        	200
#define HOVER_FRAME_attak105        	201
#define HOVER_FRAME_attak106        	202
#define HOVER_FRAME_attak107        	203
#define HOVER_FRAME_attak108        	204

#define HOVER_MODEL_SCALE		1.000000
