/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/mutant

// This file generated by ModelGen - Do NOT Modify

#define MUTANT_FRAME_attack01        	0
#define MUTANT_FRAME_attack02        	1
#define MUTANT_FRAME_attack03        	2
#define MUTANT_FRAME_attack04        	3
#define MUTANT_FRAME_attack05        	4
#define MUTANT_FRAME_attack06        	5
#define MUTANT_FRAME_attack07        	6
#define MUTANT_FRAME_attack08        	7
#define MUTANT_FRAME_attack09        	8
#define MUTANT_FRAME_attack10        	9
#define MUTANT_FRAME_attack11        	10
#define MUTANT_FRAME_attack12        	11
#define MUTANT_FRAME_attack13        	12
#define MUTANT_FRAME_attack14        	13
#define MUTANT_FRAME_attack15        	14
#define MUTANT_FRAME_death101        	15
#define MUTANT_FRAME_death102        	16
#define MUTANT_FRAME_death103        	17
#define MUTANT_FRAME_death104        	18
#define MUTANT_FRAME_death105        	19
#define MUTANT_FRAME_death106        	20
#define MUTANT_FRAME_death107        	21
#define MUTANT_FRAME_death108        	22
#define MUTANT_FRAME_death109        	23
#define MUTANT_FRAME_death201        	24
#define MUTANT_FRAME_death202        	25
#define MUTANT_FRAME_death203        	26
#define MUTANT_FRAME_death204        	27
#define MUTANT_FRAME_death205        	28
#define MUTANT_FRAME_death206        	29
#define MUTANT_FRAME_death207        	30
#define MUTANT_FRAME_death208        	31
#define MUTANT_FRAME_death209        	32
#define MUTANT_FRAME_death210        	33
#define MUTANT_FRAME_pain101         	34
#define MUTANT_FRAME_pain102         	35
#define MUTANT_FRAME_pain103         	36
#define MUTANT_FRAME_pain104         	37
#define MUTANT_FRAME_pain105         	38
#define MUTANT_FRAME_pain201         	39
#define MUTANT_FRAME_pain202         	40
#define MUTANT_FRAME_pain203         	41
#define MUTANT_FRAME_pain204         	42
#define MUTANT_FRAME_pain205         	43
#define MUTANT_FRAME_pain206         	44
#define MUTANT_FRAME_pain301         	45
#define MUTANT_FRAME_pain302         	46
#define MUTANT_FRAME_pain303         	47
#define MUTANT_FRAME_pain304         	48
#define MUTANT_FRAME_pain305         	49
#define MUTANT_FRAME_pain306         	50
#define MUTANT_FRAME_pain307         	51
#define MUTANT_FRAME_pain308         	52
#define MUTANT_FRAME_pain309         	53
#define MUTANT_FRAME_pain310         	54
#define MUTANT_FRAME_pain311         	55
#define MUTANT_FRAME_run03           	56
#define MUTANT_FRAME_run04           	57
#define MUTANT_FRAME_run05           	58
#define MUTANT_FRAME_run06           	59
#define MUTANT_FRAME_run07           	60
#define MUTANT_FRAME_run08           	61
#define MUTANT_FRAME_stand101        	62
#define MUTANT_FRAME_stand102        	63
#define MUTANT_FRAME_stand103        	64
#define MUTANT_FRAME_stand104        	65
#define MUTANT_FRAME_stand105        	66
#define MUTANT_FRAME_stand106        	67
#define MUTANT_FRAME_stand107        	68
#define MUTANT_FRAME_stand108        	69
#define MUTANT_FRAME_stand109        	70
#define MUTANT_FRAME_stand110        	71
#define MUTANT_FRAME_stand111        	72
#define MUTANT_FRAME_stand112        	73
#define MUTANT_FRAME_stand113        	74
#define MUTANT_FRAME_stand114        	75
#define MUTANT_FRAME_stand115        	76
#define MUTANT_FRAME_stand116        	77
#define MUTANT_FRAME_stand117        	78
#define MUTANT_FRAME_stand118        	79
#define MUTANT_FRAME_stand119        	80
#define MUTANT_FRAME_stand120        	81
#define MUTANT_FRAME_stand121        	82
#define MUTANT_FRAME_stand122        	83
#define MUTANT_FRAME_stand123        	84
#define MUTANT_FRAME_stand124        	85
#define MUTANT_FRAME_stand125        	86
#define MUTANT_FRAME_stand126        	87
#define MUTANT_FRAME_stand127        	88
#define MUTANT_FRAME_stand128        	89
#define MUTANT_FRAME_stand129        	90
#define MUTANT_FRAME_stand130        	91
#define MUTANT_FRAME_stand131        	92
#define MUTANT_FRAME_stand132        	93
#define MUTANT_FRAME_stand133        	94
#define MUTANT_FRAME_stand134        	95
#define MUTANT_FRAME_stand135        	96
#define MUTANT_FRAME_stand136        	97
#define MUTANT_FRAME_stand137        	98
#define MUTANT_FRAME_stand138        	99
#define MUTANT_FRAME_stand139        	100
#define MUTANT_FRAME_stand140        	101
#define MUTANT_FRAME_stand141        	102
#define MUTANT_FRAME_stand142        	103
#define MUTANT_FRAME_stand143        	104
#define MUTANT_FRAME_stand144        	105
#define MUTANT_FRAME_stand145        	106
#define MUTANT_FRAME_stand146        	107
#define MUTANT_FRAME_stand147        	108
#define MUTANT_FRAME_stand148        	109
#define MUTANT_FRAME_stand149        	110
#define MUTANT_FRAME_stand150        	111
#define MUTANT_FRAME_stand151        	112
#define MUTANT_FRAME_stand152        	113
#define MUTANT_FRAME_stand153        	114
#define MUTANT_FRAME_stand154        	115
#define MUTANT_FRAME_stand155        	116
#define MUTANT_FRAME_stand156        	117
#define MUTANT_FRAME_stand157        	118
#define MUTANT_FRAME_stand158        	119
#define MUTANT_FRAME_stand159        	120
#define MUTANT_FRAME_stand160        	121
#define MUTANT_FRAME_stand161        	122
#define MUTANT_FRAME_stand162        	123
#define MUTANT_FRAME_stand163        	124
#define MUTANT_FRAME_stand164        	125
#define MUTANT_FRAME_walk01          	126
#define MUTANT_FRAME_walk02          	127
#define MUTANT_FRAME_walk03          	128
#define MUTANT_FRAME_walk04          	129
#define MUTANT_FRAME_walk05          	130
#define MUTANT_FRAME_walk06          	131
#define MUTANT_FRAME_walk07          	132
#define MUTANT_FRAME_walk08          	133
#define MUTANT_FRAME_walk09          	134
#define MUTANT_FRAME_walk10          	135
#define MUTANT_FRAME_walk11          	136
#define MUTANT_FRAME_walk12          	137
#define MUTANT_FRAME_walk13          	138
#define MUTANT_FRAME_walk14          	139
#define MUTANT_FRAME_walk15          	140
#define MUTANT_FRAME_walk16          	141
#define MUTANT_FRAME_walk17          	142
#define MUTANT_FRAME_walk18          	143
#define MUTANT_FRAME_walk19          	144
#define MUTANT_FRAME_walk20          	145
#define MUTANT_FRAME_walk21          	146
#define MUTANT_FRAME_walk22          	147
#define MUTANT_FRAME_walk23          	148

#define MUTANT_MODEL_SCALE		1.000000
