/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/player_x/frames

// This file generated by qdata - Do NOT Modify

#define PLAYER_FRAME_stand01         	0
#define PLAYER_FRAME_stand02         	1
#define PLAYER_FRAME_stand03         	2
#define PLAYER_FRAME_stand04         	3
#define PLAYER_FRAME_stand05         	4
#define PLAYER_FRAME_stand06         	5
#define PLAYER_FRAME_stand07         	6
#define PLAYER_FRAME_stand08         	7
#define PLAYER_FRAME_stand09         	8
#define PLAYER_FRAME_stand10         	9
#define PLAYER_FRAME_stand11         	10
#define PLAYER_FRAME_stand12         	11
#define PLAYER_FRAME_stand13         	12
#define PLAYER_FRAME_stand14         	13
#define PLAYER_FRAME_stand15         	14
#define PLAYER_FRAME_stand16         	15
#define PLAYER_FRAME_stand17         	16
#define PLAYER_FRAME_stand18         	17
#define PLAYER_FRAME_stand19         	18
#define PLAYER_FRAME_stand20         	19
#define PLAYER_FRAME_stand21         	20
#define PLAYER_FRAME_stand22         	21
#define PLAYER_FRAME_stand23         	22
#define PLAYER_FRAME_stand24         	23
#define PLAYER_FRAME_stand25         	24
#define PLAYER_FRAME_stand26         	25
#define PLAYER_FRAME_stand27         	26
#define PLAYER_FRAME_stand28         	27
#define PLAYER_FRAME_stand29         	28
#define PLAYER_FRAME_stand30         	29
#define PLAYER_FRAME_stand31         	30
#define PLAYER_FRAME_stand32         	31
#define PLAYER_FRAME_stand33         	32
#define PLAYER_FRAME_stand34         	33
#define PLAYER_FRAME_stand35         	34
#define PLAYER_FRAME_stand36         	35
#define PLAYER_FRAME_stand37         	36
#define PLAYER_FRAME_stand38         	37
#define PLAYER_FRAME_stand39         	38
#define PLAYER_FRAME_stand40         	39
#define PLAYER_FRAME_run1            	40
#define PLAYER_FRAME_run2            	41
#define PLAYER_FRAME_run3            	42
#define PLAYER_FRAME_run4            	43
#define PLAYER_FRAME_run5            	44
#define PLAYER_FRAME_run6            	45
#define PLAYER_FRAME_attack1         	46
#define PLAYER_FRAME_attack2         	47
#define PLAYER_FRAME_attack3         	48
#define PLAYER_FRAME_attack4         	49
#define PLAYER_FRAME_attack5         	50
#define PLAYER_FRAME_attack6         	51
#define PLAYER_FRAME_attack7         	52
#define PLAYER_FRAME_attack8         	53
#define PLAYER_FRAME_pain101         	54
#define PLAYER_FRAME_pain102         	55
#define PLAYER_FRAME_pain103         	56
#define PLAYER_FRAME_pain104         	57
#define PLAYER_FRAME_pain201         	58
#define PLAYER_FRAME_pain202         	59
#define PLAYER_FRAME_pain203         	60
#define PLAYER_FRAME_pain204         	61
#define PLAYER_FRAME_pain301         	62
#define PLAYER_FRAME_pain302         	63
#define PLAYER_FRAME_pain303         	64
#define PLAYER_FRAME_pain304         	65
#define PLAYER_FRAME_jump1           	66
#define PLAYER_FRAME_jump2           	67
#define PLAYER_FRAME_jump3           	68
#define PLAYER_FRAME_jump4           	69
#define PLAYER_FRAME_jump5           	70
#define PLAYER_FRAME_jump6           	71
#define PLAYER_FRAME_flip01          	72
#define PLAYER_FRAME_flip02          	73
#define PLAYER_FRAME_flip03          	74
#define PLAYER_FRAME_flip04          	75
#define PLAYER_FRAME_flip05          	76
#define PLAYER_FRAME_flip06          	77
#define PLAYER_FRAME_flip07          	78
#define PLAYER_FRAME_flip08          	79
#define PLAYER_FRAME_flip09          	80
#define PLAYER_FRAME_flip10          	81
#define PLAYER_FRAME_flip11          	82
#define PLAYER_FRAME_flip12          	83
#define PLAYER_FRAME_salute01        	84
#define PLAYER_FRAME_salute02        	85
#define PLAYER_FRAME_salute03        	86
#define PLAYER_FRAME_salute04        	87
#define PLAYER_FRAME_salute05        	88
#define PLAYER_FRAME_salute06        	89
#define PLAYER_FRAME_salute07        	90
#define PLAYER_FRAME_salute08        	91
#define PLAYER_FRAME_salute09        	92
#define PLAYER_FRAME_salute10        	93
#define PLAYER_FRAME_salute11        	94
#define PLAYER_FRAME_taunt01         	95
#define PLAYER_FRAME_taunt02         	96
#define PLAYER_FRAME_taunt03         	97
#define PLAYER_FRAME_taunt04         	98
#define PLAYER_FRAME_taunt05         	99
#define PLAYER_FRAME_taunt06         	100
#define PLAYER_FRAME_taunt07         	101
#define PLAYER_FRAME_taunt08         	102
#define PLAYER_FRAME_taunt09         	103
#define PLAYER_FRAME_taunt10         	104
#define PLAYER_FRAME_taunt11         	105
#define PLAYER_FRAME_taunt12         	106
#define PLAYER_FRAME_taunt13         	107
#define PLAYER_FRAME_taunt14         	108
#define PLAYER_FRAME_taunt15         	109
#define PLAYER_FRAME_taunt16         	110
#define PLAYER_FRAME_taunt17         	111
#define PLAYER_FRAME_wave01          	112
#define PLAYER_FRAME_wave02          	113
#define PLAYER_FRAME_wave03          	114
#define PLAYER_FRAME_wave04          	115
#define PLAYER_FRAME_wave05          	116
#define PLAYER_FRAME_wave06          	117
#define PLAYER_FRAME_wave07          	118
#define PLAYER_FRAME_wave08          	119
#define PLAYER_FRAME_wave09          	120
#define PLAYER_FRAME_wave10          	121
#define PLAYER_FRAME_wave11          	122
#define PLAYER_FRAME_point01         	123
#define PLAYER_FRAME_point02         	124
#define PLAYER_FRAME_point03         	125
#define PLAYER_FRAME_point04         	126
#define PLAYER_FRAME_point05         	127
#define PLAYER_FRAME_point06         	128
#define PLAYER_FRAME_point07         	129
#define PLAYER_FRAME_point08         	130
#define PLAYER_FRAME_point09         	131
#define PLAYER_FRAME_point10         	132
#define PLAYER_FRAME_point11         	133
#define PLAYER_FRAME_point12         	134
#define PLAYER_FRAME_crstnd01        	135
#define PLAYER_FRAME_crstnd02        	136
#define PLAYER_FRAME_crstnd03        	137
#define PLAYER_FRAME_crstnd04        	138
#define PLAYER_FRAME_crstnd05        	139
#define PLAYER_FRAME_crstnd06        	140
#define PLAYER_FRAME_crstnd07        	141
#define PLAYER_FRAME_crstnd08        	142
#define PLAYER_FRAME_crstnd09        	143
#define PLAYER_FRAME_crstnd10        	144
#define PLAYER_FRAME_crstnd11        	145
#define PLAYER_FRAME_crstnd12        	146
#define PLAYER_FRAME_crstnd13        	147
#define PLAYER_FRAME_crstnd14        	148
#define PLAYER_FRAME_crstnd15        	149
#define PLAYER_FRAME_crstnd16        	150
#define PLAYER_FRAME_crstnd17        	151
#define PLAYER_FRAME_crstnd18        	152
#define PLAYER_FRAME_crstnd19        	153
#define PLAYER_FRAME_crwalk1         	154
#define PLAYER_FRAME_crwalk2         	155
#define PLAYER_FRAME_crwalk3         	156
#define PLAYER_FRAME_crwalk4         	157
#define PLAYER_FRAME_crwalk5         	158
#define PLAYER_FRAME_crwalk6         	159
#define PLAYER_FRAME_crattak1        	160
#define PLAYER_FRAME_crattak2        	161
#define PLAYER_FRAME_crattak3        	162
#define PLAYER_FRAME_crattak4        	163
#define PLAYER_FRAME_crattak5        	164
#define PLAYER_FRAME_crattak6        	165
#define PLAYER_FRAME_crattak7        	166
#define PLAYER_FRAME_crattak8        	167
#define PLAYER_FRAME_crattak9        	168
#define PLAYER_FRAME_crpain1         	169
#define PLAYER_FRAME_crpain2         	170
#define PLAYER_FRAME_crpain3         	171
#define PLAYER_FRAME_crpain4         	172
#define PLAYER_FRAME_crdeath1        	173
#define PLAYER_FRAME_crdeath2        	174
#define PLAYER_FRAME_crdeath3        	175
#define PLAYER_FRAME_crdeath4        	176
#define PLAYER_FRAME_crdeath5        	177
#define PLAYER_FRAME_death101        	178
#define PLAYER_FRAME_death102        	179
#define PLAYER_FRAME_death103        	180
#define PLAYER_FRAME_death104        	181
#define PLAYER_FRAME_death105        	182
#define PLAYER_FRAME_death106        	183
#define PLAYER_FRAME_death201        	184
#define PLAYER_FRAME_death202        	185
#define PLAYER_FRAME_death203        	186
#define PLAYER_FRAME_death204        	187
#define PLAYER_FRAME_death205        	188
#define PLAYER_FRAME_death206        	189
#define PLAYER_FRAME_death301        	190
#define PLAYER_FRAME_death302        	191
#define PLAYER_FRAME_death303        	192
#define PLAYER_FRAME_death304        	193
#define PLAYER_FRAME_death305        	194
#define PLAYER_FRAME_death306        	195
#define PLAYER_FRAME_death307        	196
#define PLAYER_FRAME_death308        	197

#define PLAYER_MODEL_SCALE		1.000000

